Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.synced_folder "..", "/open_robot_kit"
    config.vm.provision "shell", inline: "sudo apt-get -y update"
    config.vm.provision "shell", inline: "sudo apt-get -y upgrade"
    config.vm.provision "shell", inline: "sudo apt-get -y install build-essential cmake ninja-build"
end
